// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCkl_p3D_UpaiFVhz4Pu7yNrX8iOLXWJ4',
    appId: '1:986259209756:web:85d23075140eb5b0b929d9',
    messagingSenderId: '986259209756',
    projectId: 'educontrol-63d64',
    authDomain: 'educontrol-63d64.firebaseapp.com',
    storageBucket: 'educontrol-63d64.firebasestorage.app',
    measurementId: 'G-4PG3TLE583',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnXDX4Fv4D7CdaE4I7afWEdzaZtE1sbxI',
    appId: '1:986259209756:android:8ab0e5087e52c25bb929d9',
    messagingSenderId: '986259209756',
    projectId: 'educontrol-63d64',
    storageBucket: 'educontrol-63d64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpzfLh5gxLjPcGCPUjIhLiVX2QHo59Wy0',
    appId: '1:986259209756:ios:297aec577c5f6a8fb929d9',
    messagingSenderId: '986259209756',
    projectId: 'educontrol-63d64',
    storageBucket: 'educontrol-63d64.firebasestorage.app',
    iosBundleId: 'com.example.educontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpzfLh5gxLjPcGCPUjIhLiVX2QHo59Wy0',
    appId: '1:986259209756:ios:297aec577c5f6a8fb929d9',
    messagingSenderId: '986259209756',
    projectId: 'educontrol-63d64',
    storageBucket: 'educontrol-63d64.firebasestorage.app',
    iosBundleId: 'com.example.educontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCkl_p3D_UpaiFVhz4Pu7yNrX8iOLXWJ4',
    appId: '1:986259209756:web:a76991a2fae7f818b929d9',
    messagingSenderId: '986259209756',
    projectId: 'educontrol-63d64',
    authDomain: 'educontrol-63d64.firebaseapp.com',
    storageBucket: 'educontrol-63d64.firebasestorage.app',
    measurementId: 'G-13TZRPKBGW',
  );
}